export const STATUS_LABELS = {
  conversation: ["Open", "Pending", "Closed"],
  message: ["Sent", "Delivered", "Read", "Failed"],
  template: ["Draft", "Submitted", "Approved", "Rejected"],
  user: ["Active", "Away", "Offline"],
  connection: ["Connected", "Disconnected", "Needs Attention"],
  billing: ["Active", "Manual Invoice", "Past Due"],
  activity: ["Assigned", "Triggered"],
  trigger: ["Disabled"],
  workspace: ["Paid", "Overdue", "Invited", "Pending Invite", "Lead", "Contact", "Customer", "Lost"],
} as const;

export type StatusCategory = keyof typeof STATUS_LABELS;
export type StatusLabel = (typeof STATUS_LABELS)[StatusCategory][number];

export const STATUS_TONES: Record<string, "green" | "amber" | "red" | "slate"> = {
  Open: "green",
  Pending: "amber",
  Closed: "slate",
  Sent: "slate",
  Delivered: "green",
  Read: "green",
  Failed: "red",
  Draft: "slate",
  Submitted: "amber",
  Approved: "green",
  Rejected: "red",
  Active: "green",
  Away: "amber",
  Offline: "slate",
  Disabled: "slate",
  Connected: "green",
  Disconnected: "red",
  "Needs Attention": "amber",
  "Manual Invoice": "amber",
  "Past Due": "red",
  Assigned: "slate",
  Triggered: "green",
  Paid: "green",
  Overdue: "red",
  Invited: "amber",
  "Pending Invite": "amber",
  Lead: "amber",
  Contact: "slate",
  Customer: "green",
  Lost: "red",
};
