import {
  BarChart3,
  Bell,
  BotMessageSquare,
  Building2,
  CheckCircle2,
  Check,
  CheckCheck,
  ChevronDown,
  CircleCheck,
  CircleHelp,
  Clock3,
  Copy,
  CreditCard,
  Download,
  Eye,
  FileText,
  FlaskConical,
  GraduationCap,
  HelpCircle,
  Image,
  Inbox,
  LifeBuoy,
  Link2,
  Lock,
  LogOut,
  MessageCircle,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Mic,
  MinusCircle,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Power,
  RefreshCcw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  StickyNote,
  Ticket,
  Trash2,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Video,
  Workflow,
  X,
  XCircle,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type AppIcon = LucideIcon;

export const AppIcons = {
  accountSettings: Settings,
  addNote: StickyNote,
  assignAgent: UserPlus,
  attachment: Paperclip,
  billing: CreditCard,
  cannedReplies: FileText,
  chatSupport: MessageCircleQuestion,
  check: Check,
  checkDouble: CheckCheck,
  close: X,
  contact: UserRound,
  copy: Copy,
  customField: SlidersHorizontal,
  dashboard: BarChart3,
  delete: Trash2,
  document: FileText,
  download: Download,
  duplicate: Copy,
  edit: Pencil,
  empty: Inbox,
  filter: SlidersHorizontal,
  tour: GraduationCap,
  help: CircleHelp,
  helpCenter: HelpCircle,
  image: Image,
  linksAlias: Link2,
  liveChat: MessageCircle,
  logo: MessageSquareText,
  manageTeam: UsersRound,
  media: Video,
  more: MoreHorizontal,
  notifications: Bell,
  power: Power,
  profile: UserCircle,
  profileUser: User,
  rolesPermissions: ShieldCheck,
  search: Search,
  send: Send,
  signOut: LogOut,
  statusComplete: CheckCircle2,
  statusLimited: MinusCircle,
  statusUpdate: CircleCheck,
  support: LifeBuoy,
  supportTicket: Ticket,
  template: FileText,
  test: FlaskConical,
  trigger: Workflow,
  upload: Upload,
  view: Eye,
  visitorsConversion: Building2,
  voice: Mic,
  whatsapp: BotMessageSquare,
  whatsappInbox: MessagesSquare,
  workflow: Workflow,
  xStatus: XCircle,
  chevronDown: ChevronDown,
  clock: Clock3,
  lock: Lock,
  message: MessageSquare,
  messageText: MessageSquareText,
  refresh: RefreshCcw,
  sparkle: Sparkles,
  users: Users,
  userCheck: UserCheck,
} as const satisfies Record<string, LucideIcon>;
